USE hookset;

-- 200 default Hookset flies: 70 Dry, 80 Nymph, 50 Streamer.
-- userId=NULL means this is a catalog fly, not a user-created fly.
-- Hook sizes are example ranges; adjust to match your preferred catalog.
-- Each fly type uses one shared emblem image (dry.png, nymph.png, streamer.png).
-- Inserts only: does not drop tables or delete existing rows.
INSERT INTO Flies (userId, flyType, flyName, color, minSize, maxSize, flyImage, flySlug)
VALUES
    (NULL, 'Dry', 'Tan Elk Hair Caddis', 'Tan', 12, 18, 'dry.png', 'tan-elk-hair-caddis'),
    (NULL, 'Dry', 'Olive Elk Hair Caddis', 'Olive', 12, 18, 'dry.png', 'olive-elk-hair-caddis'),
    (NULL, 'Dry', 'Black Elk Hair Caddis', 'Black', 12, 18, 'dry.png', 'black-elk-hair-caddis'),
    (NULL, 'Dry', 'Brown Elk Hair Caddis', 'Brown', 12, 18, 'dry.png', 'brown-elk-hair-caddis'),
    (NULL, 'Dry', 'Gray Elk Hair Caddis', 'Gray', 12, 18, 'dry.png', 'gray-elk-hair-caddis'),
    (NULL, 'Dry', 'Tan X-Caddis', 'Tan', 14, 18, 'dry.png', 'tan-x-caddis'),
    (NULL, 'Dry', 'Olive X-Caddis', 'Olive', 14, 18, 'dry.png', 'olive-x-caddis'),
    (NULL, 'Dry', 'Brown X-Caddis', 'Brown', 14, 18, 'dry.png', 'brown-x-caddis'),
    (NULL, 'Dry', 'Black X-Caddis', 'Black', 14, 18, 'dry.png', 'black-x-caddis'),
    (NULL, 'Dry', 'Peacock Caddis', 'Peacock', 12, 18, 'dry.png', 'peacock-caddis'),
    (NULL, 'Dry', 'Gray Adams', 'Gray', 12, 20, 'dry.png', 'gray-adams'),
    (NULL, 'Dry', 'Purple Parachute Adams', 'Purple', 12, 20, 'dry.png', 'purple-parachute-adams'),
    (NULL, 'Dry', 'Gray Parachute Adams', 'Gray', 12, 20, 'dry.png', 'gray-parachute-adams'),
    (NULL, 'Dry', 'Olive Parachute Adams', 'Olive', 14, 20, 'dry.png', 'olive-parachute-adams'),
    (NULL, 'Dry', 'Brown Parachute Adams', 'Brown', 12, 20, 'dry.png', 'brown-parachute-adams'),
    (NULL, 'Dry', 'Rusty Comparadun', 'Rust', 14, 20, 'dry.png', 'rusty-comparadun'),
    (NULL, 'Dry', 'Olive Comparadun', 'Olive', 14, 20, 'dry.png', 'olive-comparadun'),
    (NULL, 'Dry', 'Gray Comparadun', 'Gray', 14, 20, 'dry.png', 'gray-comparadun'),
    (NULL, 'Dry', 'Cream Comparadun', 'Cream', 14, 20, 'dry.png', 'cream-comparadun'),
    (NULL, 'Dry', 'Blue Wing Olive', 'Olive', 16, 22, 'dry.png', 'blue-wing-olive'),
    (NULL, 'Dry', 'Olive Parachute BWO', 'Olive', 16, 22, 'dry.png', 'olive-parachute-bwo'),
    (NULL, 'Dry', 'Gray Sparkle Dun', 'Gray', 14, 20, 'dry.png', 'gray-sparkle-dun'),
    (NULL, 'Dry', 'Olive Sparkle Dun', 'Olive', 16, 22, 'dry.png', 'olive-sparkle-dun'),
    (NULL, 'Dry', 'Rusty Sparkle Dun', 'Rust', 14, 20, 'dry.png', 'rusty-sparkle-dun'),
    (NULL, 'Dry', 'Cream Sparkle Dun', 'Cream', 14, 20, 'dry.png', 'cream-sparkle-dun'),
    (NULL, 'Dry', 'Yellow PMD Sparkle Dun', 'Yellow', 16, 20, 'dry.png', 'yellow-pmd-sparkle-dun'),
    (NULL, 'Dry', 'Pale Yellow PMD', 'Yellow', 16, 20, 'dry.png', 'pale-yellow-pmd'),
    (NULL, 'Dry', 'Pink PMD Cripple', 'Pink', 16, 20, 'dry.png', 'pink-pmd-cripple'),
    (NULL, 'Dry', 'Yellow PMD Cripple', 'Yellow', 16, 20, 'dry.png', 'yellow-pmd-cripple'),
    (NULL, 'Dry', 'Olive BWO Cripple', 'Olive', 18, 22, 'dry.png', 'olive-bwo-cripple'),
    (NULL, 'Dry', 'Yellow Stimulator', 'Yellow', 8, 16, 'dry.png', 'yellow-stimulator'),
    (NULL, 'Dry', 'Orange Stimulator', 'Orange', 8, 16, 'dry.png', 'orange-stimulator'),
    (NULL, 'Dry', 'Royal Stimulator', 'Red', 8, 16, 'dry.png', 'royal-stimulator'),
    (NULL, 'Dry', 'Olive Stimulator', 'Olive', 8, 16, 'dry.png', 'olive-stimulator'),
    (NULL, 'Dry', 'Tan Stimulator', 'Tan', 8, 16, 'dry.png', 'tan-stimulator'),
    (NULL, 'Dry', 'Golden Stone Chubby Chernobyl', 'Golden', 6, 12, 'dry.png', 'golden-stone-chubby-chernobyl'),
    (NULL, 'Dry', 'Purple Chubby Chernobyl', 'Purple', 6, 12, 'dry.png', 'purple-chubby-chernobyl'),
    (NULL, 'Dry', 'Black Chubby Chernobyl', 'Black', 6, 12, 'dry.png', 'black-chubby-chernobyl'),
    (NULL, 'Dry', 'Pink Chubby Chernobyl', 'Pink', 6, 12, 'dry.png', 'pink-chubby-chernobyl'),
    (NULL, 'Dry', 'Tan Chubby Chernobyl', 'Tan', 6, 12, 'dry.png', 'tan-chubby-chernobyl'),
    (NULL, 'Dry', 'Yellow Sally Dry', 'Yellow', 12, 18, 'dry.png', 'yellow-sally-dry'),
    (NULL, 'Dry', 'Orange Foam Sally', 'Orange', 12, 18, 'dry.png', 'orange-foam-sally'),
    (NULL, 'Dry', 'Black Foam Ant', 'Black', 14, 20, 'dry.png', 'black-foam-ant'),
    (NULL, 'Dry', 'Cinnamon Foam Ant', 'Cinnamon', 14, 20, 'dry.png', 'cinnamon-foam-ant'),
    (NULL, 'Dry', 'Red Foam Ant', 'Red', 14, 20, 'dry.png', 'red-foam-ant'),
    (NULL, 'Dry', 'Black Beetle', 'Black', 12, 18, 'dry.png', 'black-beetle'),
    (NULL, 'Dry', 'Brown Beetle', 'Brown', 12, 18, 'dry.png', 'brown-beetle'),
    (NULL, 'Dry', 'Green Foam Beetle', 'Green', 12, 18, 'dry.png', 'green-foam-beetle'),
    (NULL, 'Dry', 'Yellow Hopper', 'Yellow', 6, 12, 'dry.png', 'yellow-hopper'),
    (NULL, 'Dry', 'Tan Hopper', 'Tan', 6, 12, 'dry.png', 'tan-hopper'),
    (NULL, 'Dry', 'Pink Hopper', 'Pink', 6, 12, 'dry.png', 'pink-hopper'),
    (NULL, 'Dry', 'Olive Hopper', 'Olive', 6, 12, 'dry.png', 'olive-hopper'),
    (NULL, 'Dry', 'Brown Dave Hopper', 'Brown', 6, 12, 'dry.png', 'brown-dave-hopper'),
    (NULL, 'Dry', 'Yellow Morrish Hopper', 'Yellow', 6, 12, 'dry.png', 'yellow-morrish-hopper'),
    (NULL, 'Dry', 'Tan Morrish Hopper', 'Tan', 6, 12, 'dry.png', 'tan-morrish-hopper'),
    (NULL, 'Dry', 'Black Cricket', 'Black', 8, 14, 'dry.png', 'black-cricket'),
    (NULL, 'Dry', 'Brown Cricket', 'Brown', 8, 14, 'dry.png', 'brown-cricket'),
    (NULL, 'Dry', 'Green Chernobyl Ant', 'Green', 6, 12, 'dry.png', 'green-chernobyl-ant'),
    (NULL, 'Dry', 'Black Chernobyl Ant', 'Black', 6, 12, 'dry.png', 'black-chernobyl-ant'),
    (NULL, 'Dry', 'Purple Amy''s Ant', 'Purple', 8, 12, 'dry.png', 'purple-amys-ant'),
    (NULL, 'Dry', 'Royal Wulff Red', 'Red', 10, 16, 'dry.png', 'royal-wulff-red'),
    (NULL, 'Dry', 'White Wulff', 'White', 10, 16, 'dry.png', 'white-wulff'),
    (NULL, 'Dry', 'Gray Wulff', 'Gray', 10, 16, 'dry.png', 'gray-wulff'),
    (NULL, 'Dry', 'Brown Humpy', 'Brown', 10, 16, 'dry.png', 'brown-humpy'),
    (NULL, 'Dry', 'Yellow Humpy', 'Yellow', 10, 16, 'dry.png', 'yellow-humpy'),
    (NULL, 'Dry', 'Royal Humpy Red', 'Red', 10, 16, 'dry.png', 'royal-humpy-red'),
    (NULL, 'Dry', 'Orange Trude', 'Orange', 10, 16, 'dry.png', 'orange-trude'),
    (NULL, 'Dry', 'Yellow Trude', 'Yellow', 10, 16, 'dry.png', 'yellow-trude'),
    (NULL, 'Dry', 'Black Griffith''s Gnat', 'Black', 18, 24, 'dry.png', 'black-griffiths-gnat'),
    (NULL, 'Dry', 'Gray Midge Cluster', 'Gray', 18, 24, 'dry.png', 'gray-midge-cluster'),
    (NULL, 'Nymph', 'Gold Bead Pheasant Tail', 'Brown', 12, 20, 'nymph.png', 'gold-bead-pheasant-tail'),
    (NULL, 'Nymph', 'Flashback Pheasant Tail Brown', 'Brown', 14, 20, 'nymph.png', 'flashback-pheasant-tail-brown'),
    (NULL, 'Nymph', 'Olive Pheasant Tail', 'Olive', 14, 20, 'nymph.png', 'olive-pheasant-tail'),
    (NULL, 'Nymph', 'Black Pheasant Tail', 'Black', 14, 20, 'nymph.png', 'black-pheasant-tail'),
    (NULL, 'Nymph', 'Pink Pheasant Tail', 'Pink', 14, 20, 'nymph.png', 'pink-pheasant-tail'),
    (NULL, 'Nymph', 'Purple Pheasant Tail', 'Purple', 14, 20, 'nymph.png', 'purple-pheasant-tail'),
    (NULL, 'Nymph', 'Brown Soft Hackle Pheasant Tail', 'Brown', 12, 18, 'nymph.png', 'brown-soft-hackle-pheasant-tail'),
    (NULL, 'Nymph', 'Olive Soft Hackle Pheasant Tail', 'Olive', 14, 20, 'nymph.png', 'olive-soft-hackle-pheasant-tail'),
    (NULL, 'Nymph', 'Copper Bead Pheasant Tail Brown', 'Brown', 12, 18, 'nymph.png', 'copper-bead-pheasant-tail-brown'),
    (NULL, 'Nymph', 'Red Hot Spot Pheasant Tail', 'Red', 14, 20, 'nymph.png', 'red-hot-spot-pheasant-tail'),
    (NULL, 'Nymph', 'Gold Ribbed Hare''s Ear Tan', 'Tan', 10, 18, 'nymph.png', 'gold-ribbed-hares-ear-tan'),
    (NULL, 'Nymph', 'Olive Hare''s Ear', 'Olive', 12, 18, 'nymph.png', 'olive-hares-ear'),
    (NULL, 'Nymph', 'Dark Brown Hare''s Ear', 'Brown', 12, 18, 'nymph.png', 'dark-brown-hares-ear'),
    (NULL, 'Nymph', 'Black Hare''s Ear', 'Black', 12, 18, 'nymph.png', 'black-hares-ear'),
    (NULL, 'Nymph', 'Flashback Hare''s Ear Tan', 'Tan', 12, 18, 'nymph.png', 'flashback-hares-ear-tan'),
    (NULL, 'Nymph', 'Pink Hot Spot Hare''s Ear', 'Pink', 12, 18, 'nymph.png', 'pink-hot-spot-hares-ear'),
    (NULL, 'Nymph', 'Gold Bead Hare''s Ear Brown', 'Brown', 10, 18, 'nymph.png', 'gold-bead-hares-ear-brown'),
    (NULL, 'Nymph', 'Orange Hot Spot Hare''s Ear', 'Orange', 12, 18, 'nymph.png', 'orange-hot-spot-hares-ear'),
    (NULL, 'Nymph', 'Cream Hare''s Ear', 'Cream', 12, 18, 'nymph.png', 'cream-hares-ear'),
    (NULL, 'Nymph', 'Gray Hare''s Ear', 'Gray', 12, 18, 'nymph.png', 'gray-hares-ear'),
    (NULL, 'Nymph', 'Black Zebra Midge', 'Black', 16, 24, 'nymph.png', 'black-zebra-midge'),
    (NULL, 'Nymph', 'Red Zebra Midge', 'Red', 16, 24, 'nymph.png', 'red-zebra-midge'),
    (NULL, 'Nymph', 'Olive Zebra Midge', 'Olive', 16, 24, 'nymph.png', 'olive-zebra-midge'),
    (NULL, 'Nymph', 'Purple Zebra Midge', 'Purple', 16, 24, 'nymph.png', 'purple-zebra-midge'),
    (NULL, 'Nymph', 'Brown Zebra Midge', 'Brown', 16, 24, 'nymph.png', 'brown-zebra-midge'),
    (NULL, 'Nymph', 'Cream Zebra Midge', 'Cream', 16, 24, 'nymph.png', 'cream-zebra-midge'),
    (NULL, 'Nymph', 'Black and Silver Zebra Midge', 'Black/Silver', 16, 24, 'nymph.png', 'black-and-silver-zebra-midge'),
    (NULL, 'Nymph', 'Red and Silver Zebra Midge', 'Red/Silver', 16, 24, 'nymph.png', 'red-and-silver-zebra-midge'),
    (NULL, 'Nymph', 'Olive and Copper Zebra Midge', 'Olive/Copper', 16, 24, 'nymph.png', 'olive-and-copper-zebra-midge'),
    (NULL, 'Nymph', 'Pink Zebra Midge', 'Pink', 16, 24, 'nymph.png', 'pink-zebra-midge'),
    (NULL, 'Nymph', 'Black Copper John', 'Black', 12, 20, 'nymph.png', 'black-copper-john'),
    (NULL, 'Nymph', 'Red Copper John', 'Red', 12, 20, 'nymph.png', 'red-copper-john'),
    (NULL, 'Nymph', 'Green Copper John', 'Green', 12, 20, 'nymph.png', 'green-copper-john'),
    (NULL, 'Nymph', 'Copper Copper John', 'Copper', 12, 20, 'nymph.png', 'copper-copper-john'),
    (NULL, 'Nymph', 'Blue Copper John', 'Blue', 12, 20, 'nymph.png', 'blue-copper-john'),
    (NULL, 'Nymph', 'Purple Copper John', 'Purple', 12, 20, 'nymph.png', 'purple-copper-john'),
    (NULL, 'Nymph', 'Chartreuse Copper John', 'Chartreuse', 12, 20, 'nymph.png', 'chartreuse-copper-john'),
    (NULL, 'Nymph', 'Black Brassie', 'Black', 16, 22, 'nymph.png', 'black-brassie'),
    (NULL, 'Nymph', 'Red Brassie', 'Red', 16, 22, 'nymph.png', 'red-brassie'),
    (NULL, 'Nymph', 'Copper Brassie', 'Copper', 16, 22, 'nymph.png', 'copper-brassie'),
    (NULL, 'Nymph', 'Olive Perdigon', 'Olive', 14, 20, 'nymph.png', 'olive-perdigon'),
    (NULL, 'Nymph', 'Black Perdigon', 'Black', 14, 20, 'nymph.png', 'black-perdigon'),
    (NULL, 'Nymph', 'Purple Perdigon', 'Purple', 14, 20, 'nymph.png', 'purple-perdigon'),
    (NULL, 'Nymph', 'Brown Perdigon', 'Brown', 14, 20, 'nymph.png', 'brown-perdigon'),
    (NULL, 'Nymph', 'Pink Hot Spot Perdigon', 'Pink', 14, 20, 'nymph.png', 'pink-hot-spot-perdigon'),
    (NULL, 'Nymph', 'Orange Hot Spot Perdigon', 'Orange', 14, 20, 'nymph.png', 'orange-hot-spot-perdigon'),
    (NULL, 'Nymph', 'Frenchie Pink Hot Spot', 'Pink', 14, 20, 'nymph.png', 'frenchie-pink-hot-spot'),
    (NULL, 'Nymph', 'Frenchie Orange Hot Spot', 'Orange', 14, 20, 'nymph.png', 'frenchie-orange-hot-spot'),
    (NULL, 'Nymph', 'Purple Frenchie', 'Purple', 14, 20, 'nymph.png', 'purple-frenchie'),
    (NULL, 'Nymph', 'Olive Frenchie', 'Olive', 14, 20, 'nymph.png', 'olive-frenchie'),
    (NULL, 'Nymph', 'Black Pat''s Rubber Legs', 'Black', 4, 12, 'nymph.png', 'black-pats-rubber-legs'),
    (NULL, 'Nymph', 'Brown Pat''s Rubber Legs', 'Brown', 4, 12, 'nymph.png', 'brown-pats-rubber-legs'),
    (NULL, 'Nymph', 'Olive Pat''s Rubber Legs', 'Olive', 4, 12, 'nymph.png', 'olive-pats-rubber-legs'),
    (NULL, 'Nymph', 'Coffee Pat''s Rubber Legs', 'Coffee', 4, 12, 'nymph.png', 'coffee-pats-rubber-legs'),
    (NULL, 'Nymph', 'Golden Stone Rubber Legs', 'Golden', 6, 12, 'nymph.png', 'golden-stone-rubber-legs'),
    (NULL, 'Nymph', 'Yellow Stonefly Nymph', 'Yellow', 6, 12, 'nymph.png', 'yellow-stonefly-nymph'),
    (NULL, 'Nymph', 'Black Stonefly Nymph', 'Black', 6, 12, 'nymph.png', 'black-stonefly-nymph'),
    (NULL, 'Nymph', 'Brown Stonefly Nymph', 'Brown', 6, 12, 'nymph.png', 'brown-stonefly-nymph'),
    (NULL, 'Nymph', 'Olive Stonefly Nymph', 'Olive', 6, 12, 'nymph.png', 'olive-stonefly-nymph'),
    (NULL, 'Nymph', 'Orange Hot Spot Stonefly', 'Orange', 6, 12, 'nymph.png', 'orange-hot-spot-stonefly'),
    (NULL, 'Nymph', 'Green Caddis Pupa', 'Green', 12, 18, 'nymph.png', 'green-caddis-pupa'),
    (NULL, 'Nymph', 'Tan Caddis Pupa', 'Tan', 12, 18, 'nymph.png', 'tan-caddis-pupa'),
    (NULL, 'Nymph', 'Olive Caddis Pupa', 'Olive', 12, 18, 'nymph.png', 'olive-caddis-pupa'),
    (NULL, 'Nymph', 'Brown Caddis Pupa', 'Brown', 12, 18, 'nymph.png', 'brown-caddis-pupa'),
    (NULL, 'Nymph', 'Cream Caddis Larva', 'Cream', 12, 20, 'nymph.png', 'cream-caddis-larva'),
    (NULL, 'Nymph', 'Green Caddis Larva', 'Green', 12, 20, 'nymph.png', 'green-caddis-larva'),
    (NULL, 'Nymph', 'Olive Walt''s Worm', 'Olive', 12, 18, 'nymph.png', 'olive-walts-worm'),
    (NULL, 'Nymph', 'Tan Walt''s Worm', 'Tan', 12, 18, 'nymph.png', 'tan-walts-worm'),
    (NULL, 'Nymph', 'Pink Hot Spot Walt''s Worm', 'Pink', 12, 18, 'nymph.png', 'pink-hot-spot-walts-worm'),
    (NULL, 'Nymph', 'Brown Soft Hackle Caddis', 'Brown', 12, 18, 'nymph.png', 'brown-soft-hackle-caddis'),
    (NULL, 'Nymph', 'Pink San Juan Worm', 'Pink', 10, 16, 'nymph.png', 'pink-san-juan-worm'),
    (NULL, 'Nymph', 'Red San Juan Worm', 'Red', 10, 16, 'nymph.png', 'red-san-juan-worm'),
    (NULL, 'Nymph', 'Brown San Juan Worm', 'Brown', 10, 16, 'nymph.png', 'brown-san-juan-worm'),
    (NULL, 'Nymph', 'Purple San Juan Worm', 'Purple', 10, 16, 'nymph.png', 'purple-san-juan-worm'),
    (NULL, 'Nymph', 'Peach Egg Pattern', 'Peach', 10, 16, 'nymph.png', 'peach-egg-pattern'),
    (NULL, 'Nymph', 'Orange Egg Pattern', 'Orange', 10, 16, 'nymph.png', 'orange-egg-pattern'),
    (NULL, 'Nymph', 'Pink Egg Pattern', 'Pink', 10, 16, 'nymph.png', 'pink-egg-pattern'),
    (NULL, 'Nymph', 'Chartreuse Egg Pattern', 'Chartreuse', 10, 16, 'nymph.png', 'chartreuse-egg-pattern'),
    (NULL, 'Nymph', 'Black WD-40', 'Black', 18, 24, 'nymph.png', 'black-wd-40'),
    (NULL, 'Nymph', 'Olive WD-40', 'Olive', 18, 24, 'nymph.png', 'olive-wd-40'),
    (NULL, 'Streamer', 'Black Woolly Bugger', 'Black', 4, 10, 'streamer.png', 'black-woolly-bugger'),
    (NULL, 'Streamer', 'Olive Woolly Bugger', 'Olive', 4, 10, 'streamer.png', 'olive-woolly-bugger'),
    (NULL, 'Streamer', 'Brown Woolly Bugger', 'Brown', 4, 10, 'streamer.png', 'brown-woolly-bugger'),
    (NULL, 'Streamer', 'White Woolly Bugger', 'White', 4, 10, 'streamer.png', 'white-woolly-bugger'),
    (NULL, 'Streamer', 'Purple Woolly Bugger', 'Purple', 4, 10, 'streamer.png', 'purple-woolly-bugger'),
    (NULL, 'Streamer', 'Black and Olive Woolly Bugger', 'Black/Olive', 4, 10, 'streamer.png', 'black-and-olive-woolly-bugger'),
    (NULL, 'Streamer', 'Yellow Woolly Bugger', 'Yellow', 4, 10, 'streamer.png', 'yellow-woolly-bugger'),
    (NULL, 'Streamer', 'Orange Woolly Bugger', 'Orange', 4, 10, 'streamer.png', 'orange-woolly-bugger'),
    (NULL, 'Streamer', 'Peacock Woolly Bugger', 'Peacock', 4, 10, 'streamer.png', 'peacock-woolly-bugger'),
    (NULL, 'Streamer', 'Black and Red Woolly Bugger', 'Black/Red', 4, 10, 'streamer.png', 'black-and-red-woolly-bugger'),
    (NULL, 'Streamer', 'Olive Sculpzilla', 'Olive', 4, 8, 'streamer.png', 'olive-sculpzilla'),
    (NULL, 'Streamer', 'Black Sculpzilla', 'Black', 4, 8, 'streamer.png', 'black-sculpzilla'),
    (NULL, 'Streamer', 'Brown Sculpzilla', 'Brown', 4, 8, 'streamer.png', 'brown-sculpzilla'),
    (NULL, 'Streamer', 'White Sculpzilla', 'White', 4, 8, 'streamer.png', 'white-sculpzilla'),
    (NULL, 'Streamer', 'Tan Sculpzilla', 'Tan', 4, 8, 'streamer.png', 'tan-sculpzilla'),
    (NULL, 'Streamer', 'Olive Sculpin', 'Olive', 2, 8, 'streamer.png', 'olive-sculpin'),
    (NULL, 'Streamer', 'Brown Sculpin', 'Brown', 2, 8, 'streamer.png', 'brown-sculpin'),
    (NULL, 'Streamer', 'Black Sculpin', 'Black', 2, 8, 'streamer.png', 'black-sculpin'),
    (NULL, 'Streamer', 'Tan Sculpin', 'Tan', 2, 8, 'streamer.png', 'tan-sculpin'),
    (NULL, 'Streamer', 'Gray Sculpin', 'Gray', 2, 8, 'streamer.png', 'gray-sculpin'),
    (NULL, 'Streamer', 'White Zonker', 'White', 2, 8, 'streamer.png', 'white-zonker'),
    (NULL, 'Streamer', 'Black Zonker', 'Black', 2, 8, 'streamer.png', 'black-zonker'),
    (NULL, 'Streamer', 'Olive Zonker', 'Olive', 2, 8, 'streamer.png', 'olive-zonker'),
    (NULL, 'Streamer', 'Brown Zonker', 'Brown', 2, 8, 'streamer.png', 'brown-zonker'),
    (NULL, 'Streamer', 'Purple Zonker', 'Purple', 2, 8, 'streamer.png', 'purple-zonker'),
    (NULL, 'Streamer', 'White Rabbit Strip Leech', 'White', 2, 8, 'streamer.png', 'white-rabbit-strip-leech'),
    (NULL, 'Streamer', 'Black Rabbit Strip Leech', 'Black', 2, 8, 'streamer.png', 'black-rabbit-strip-leech'),
    (NULL, 'Streamer', 'Olive Rabbit Strip Leech', 'Olive', 2, 8, 'streamer.png', 'olive-rabbit-strip-leech'),
    (NULL, 'Streamer', 'Purple Rabbit Strip Leech', 'Purple', 2, 8, 'streamer.png', 'purple-rabbit-strip-leech'),
    (NULL, 'Streamer', 'Wine Rabbit Strip Leech', 'Wine', 2, 8, 'streamer.png', 'wine-rabbit-strip-leech'),
    (NULL, 'Streamer', 'White Sex Dungeon', 'White', 2, 6, 'streamer.png', 'white-sex-dungeon'),
    (NULL, 'Streamer', 'Olive Sex Dungeon', 'Olive', 2, 6, 'streamer.png', 'olive-sex-dungeon'),
    (NULL, 'Streamer', 'Black Sex Dungeon', 'Black', 2, 6, 'streamer.png', 'black-sex-dungeon'),
    (NULL, 'Streamer', 'Yellow Sex Dungeon', 'Yellow', 2, 6, 'streamer.png', 'yellow-sex-dungeon'),
    (NULL, 'Streamer', 'Brown Sex Dungeon', 'Brown', 2, 6, 'streamer.png', 'brown-sex-dungeon'),
    (NULL, 'Streamer', 'Black Circus Peanut', 'Black', 2, 6, 'streamer.png', 'black-circus-peanut'),
    (NULL, 'Streamer', 'Olive Circus Peanut', 'Olive', 2, 6, 'streamer.png', 'olive-circus-peanut'),
    (NULL, 'Streamer', 'White Circus Peanut', 'White', 2, 6, 'streamer.png', 'white-circus-peanut'),
    (NULL, 'Streamer', 'Yellow Circus Peanut', 'Yellow', 2, 6, 'streamer.png', 'yellow-circus-peanut'),
    (NULL, 'Streamer', 'Tan Circus Peanut', 'Tan', 2, 6, 'streamer.png', 'tan-circus-peanut'),
    (NULL, 'Streamer', 'White Clouser Minnow', 'White', 2, 8, 'streamer.png', 'white-clouser-minnow'),
    (NULL, 'Streamer', 'Chartreuse and White Clouser Minnow', 'Chartreuse/White', 2, 8, 'streamer.png', 'chartreuse-and-white-clouser-minnow'),
    (NULL, 'Streamer', 'Olive Clouser Minnow', 'Olive', 2, 8, 'streamer.png', 'olive-clouser-minnow'),
    (NULL, 'Streamer', 'Gray Clouser Minnow', 'Gray', 2, 8, 'streamer.png', 'gray-clouser-minnow'),
    (NULL, 'Streamer', 'Black Clouser Minnow', 'Black', 2, 8, 'streamer.png', 'black-clouser-minnow'),
    (NULL, 'Streamer', 'Silver Muddler Minnow', 'Silver', 4, 10, 'streamer.png', 'silver-muddler-minnow'),
    (NULL, 'Streamer', 'Brown Muddler Minnow', 'Brown', 4, 10, 'streamer.png', 'brown-muddler-minnow'),
    (NULL, 'Streamer', 'Olive Muddler Minnow', 'Olive', 4, 10, 'streamer.png', 'olive-muddler-minnow'),
    (NULL, 'Streamer', 'Black Muddler Minnow', 'Black', 4, 10, 'streamer.png', 'black-muddler-minnow'),
    (NULL, 'Streamer', 'Gold Muddler Minnow', 'Gold', 4, 10, 'streamer.png', 'gold-muddler-minnow');
