package edu.carroll.cs341.hookset.jpa.entity;
/**
 * Represents a user stored in the Hookset database.
 * Contains the user's unique ID, username, hashed password,
 * and administrator status.
 *
 * <p>
 * Sources used:
 * <br>
 * Documentation on using {@code @Column} when the database column name
 * differs from the Java variable name:
 * <a href="https://www.baeldung.com/java-hibernate-db-keywords-as-columns">
 * Baeldung - Hibernate Database Keywords as Columns
 * </a>
 * </p>
 */

import jakarta.persistence.*;

/**
 * Represents a user stored in the Hookset database.
 * This entity contains the user's ID, username, hashed password,
 * and administrator status.
 */
@Entity
public class User {

    /**
     * Unique identifier for the user.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "User_ID")
    private int userId;

    /**
     * Username used to identify the user.
     */
    @Column(name = "Username")
    private String username;

    /**
     * Stores the hashed version of the user's password.
     */
    @Column(name = "Hash_Password")
    private String hashPassword;

    /**
     * Indicates whether the user has administrator privileges.
     */
    @Column(name = "Is_Admin")
    private boolean isAdmin;

    /**
     * Gets the user's unique ID.
     *
     * @return the user's ID
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Gets the user's hashed password.
     *
     * @return the hashed password
     */
    public String getHashPassword() {
        return hashPassword;
    }

    /**
     * Gets the user's username.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Gets whether the user has administrator privileges.
     *
     * @return true if the user is an administrator, otherwise false
     */
    public boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * Sets the user's username.
     *
     * @param username the username to assign to the user
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Sets the user's hashed password.
     *
     * @param hashPassword the hashed password to store
     */
    public void setHashPassword(String hashPassword) {
        this.hashPassword = hashPassword;
    }

    /**
     * Sets whether the user has administrator privileges.
     *
     * @param isAdmin true if the user should be an administrator, otherwise false
     */
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
}