spring.application.name=hookset

spring.datasource.url=jdbc:mysql://localhost:3306/hookset
spring.datasource.username=hooksetapp
spring.datasource.password=${HOOKSET_DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true