spring.application.name=hookset
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Hookset;encrypt=true;trustServerCertificate=true
spring.datasource.username=hookset_admin
spring.datasource.password=y6WhjUAnk5oFg85aOA8F
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true