plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Shared JPA entities
    implementation project(':shared')

    // Lets us use WebClient to call Montana APIs
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // JPA repositories for interacting with Hookset MySQL
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // MySQL JDBC driver
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}