plugins {
    // see the 'shared' package as a Java Library module, sinced shared package only holds reusable code
    id 'java-library'
}

version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'jakarta.persistence:jakarta.persistence-api:3.2.0'
}